# Generated by Django 3.2.4 on 2021-06-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='photos',
            field=models.ManyToManyField(related_name='tags', to='main.Photo'),
        ),
    ]
