# Generated by Django 3.2.4 on 2021-06-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tag_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='photos',
        ),
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(related_name='photos', to='main.Tag'),
        ),
    ]
